<?php
/**
 * Copyright © 2015 AddShoppers.com
 * @autor eduedeleon
 * */
?>
<!-- Begin AddShopers Tracking Code-->
<script type="text/javascript">
	var js = document.createElement('script'); js.type = 'text/javascript'; js.async = true; js.id = 'AddShoppers';
	js.src = ('https:' == document.location.protocol ? 'https://shop.pe/widget/' : 'http://cdn.shop.pe/widget/') + 'widget_async.js#<?php echo $block->getHelper()->getShopId(); ?>';
	document.getElementsByTagName("head")[0].appendChild(js);
</script>
<!-- End AddShopers Tracking Code-->