<?php
/**
 * Copyright © 2015 AddShoppers.com
 * @autor eduedeleon
 * */
?>

<script type="text/javascript"> 
// Init code					
function init() {
   AddShoppersWidget.API.Event.bind("sign_in", createAccount);    
};
// Create Account 
function createAccount(params) {  
   if (params.source == "social_login") {       
    services = ['facebook', 'google', 'linkedin', 'twitter', 'paypal'];
    var data = AddShoppersWidget.API.User.signed_data(); 
    for( var i=0; i < services.length; i++ ) {        
      service = services[i];
      if (AddShoppersWidget.API.User.signed(service)) {
            var email = data[service + '_email'];
            if (service == 'twitter') {
                //alert('popup get email'); 
                var email = prompt("Please enter your email", "");
            };
            if (email) {
                if (service !='twitter' ) {          
                  var name = data[service + '_firstname'] + '_' + data[service + '_lastname']; 
                } else {
                var name = data[service + '_name']; 
                };
            name = name.replace(/ /g, '­-');
                var loc = "<?php echo $block->getBaseUrl() ?>social_login/?asusrnm=" + name + "&aseml=" + email + "&data=" + JSON.stringify(data);
              document.getElementById("createme").src = loc;
              break; 
            };
        }; 
      };  
    };        
}
          
// Bind events
if (window.addEventListener) {      
   window.addEventListener("load", init, false); 
} else {
   document.onreadystatechange = function() { 
    if(document.readyState in {loaded: 1, complete: 1}) {
	document.onreadystatechange = null; 
       init();			
    } 
  }					
} 
</script>					
<iframe id="createme" src="about:blank" width="0" height="0" frameborder="0" scrolling="no"></iframe>

<div style="text-align: center;">
    <?php /* <!-- Put your Social Shopper Login button code here. Facebook is already included for this example. -->  */?>
    
    <?php if($block->getHelper()->isFacebookEnabled()) { ?>
    <!-- Facebook -->
    <div class="social-commerce-signin-facebook" data-style="logoandtext" data-size="small"></div>
    <?php } ?>

    <?php if($block->getHelper()->isPaypalEnabled()) { ?>
    <!-- Paypal -->
    <div class="social-commerce-signin-paypal" data-style="logoandtext" data-size="small"></div>
    <?php } ?>

    <?php if($block->getHelper()->isLinkedInEnabled()) { ?>
    <!--LinkedIn -->				
    <div class="social-commerce-signin-linkedin" data-style="logoandtext" data-size="small"></div>
    <?php } ?>

    <?php if($block->getHelper()->isGoogleEnabled()) { ?>
    <!-- Google -->				
    <div class="social-commerce-signin-google" data-style="logoandtext" data-size="small"></div>
    <?php } ?>

    <br>
    <div style="width: 315px; float:right;">
    Please click the sign in with any social button above and login to your account.
    </div>
</div>